// <auto-generated />
using System;
using BookManagementWeb.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookManagementWeb.Migrations
{
    [DbContext(typeof(BookstoreDbContext))]
    [Migration("20231221114906_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("BookManagementWeb.Models.Entities.CTHoaDon", b =>
                {
                    b.Property<int>("MaHoaDon")
                        .HasColumnType("int");

                    b.Property<int>("MaSach")
                        .HasColumnType("int");

                    b.Property<decimal>("DonGiaBan")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SoLuongBan")
                        .HasColumnType("int");

                    b.HasKey("MaHoaDon", "MaSach");

                    b.HasIndex("MaSach");

                    b.ToTable("CTHOADONBANSACH");
                });

            modelBuilder.Entity("BookManagementWeb.Models.Entities.CTPhieuNhapSach", b =>
                {
                    b.Property<int>("MaPhieuNhapSach")
                        .HasColumnType("int");

                    b.Property<int>("MaSach")
                        .HasColumnType("int");

                    b.Property<decimal>("DonGiaNhap")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SoLuongNhap")
                        .HasColumnType("int");

                    b.HasKey("MaPhieuNhapSach", "MaSach");

                    b.HasIndex("MaSach");

                    b.ToTable("CTPHIEUNHAPSACH");
                });

            modelBuilder.Entity("BookManagementWeb.Models.Entities.HoaDon", b =>
                {
                    b.Property<int>("MaHoaDon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaHoaDon"), 1L, 1);

                    b.Property<int>("MaKhachHang")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayLapHoaDon")
                        .HasColumnType("date");

                    b.HasKey("MaHoaDon");

                    b.HasIndex("MaKhachHang");

                    b.ToTable("HOADONBANSACH");
                });

            modelBuilder.Entity("BookManagementWeb.Models.Entities.KhachHang", b =>
                {
                    b.Property<int>("MaKhachHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaKhachHang"), 1L, 1);

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("GioiTinh")
                        .HasColumnType("bit");

                    b.Property<string>("HoVaTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SDT")
                        .IsRequired()
                        .HasColumnType("nvarchar(15)");

                    b.Property<decimal>("SoTienNo")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("MaKhachHang");

                    b.ToTable("KHACHHANG");
                });

            modelBuilder.Entity("BookManagementWeb.Models.Entities.PhieuNhapSach", b =>
                {
                    b.Property<int>("MaPhieuNhapSach")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaPhieuNhapSach"), 1L, 1);

                    b.Property<DateTime>("NgayLapPhieuNhap")
                        .HasColumnType("date");

                    b.HasKey("MaPhieuNhapSach");

                    b.ToTable("PHIEUNHAPSACH");
                });

            modelBuilder.Entity("BookManagementWeb.Models.Entities.PhieuThuTien", b =>
                {
                    b.Property<int>("MaPhieuThuTien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaPhieuThuTien"), 1L, 1);

                    b.Property<int>("MaHoaDon")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayLapPhieuThuTien")
                        .HasColumnType("date");

                    b.Property<decimal>("SoTienKhachNo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TongSoTienThu")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("MaPhieuThuTien");

                    b.HasIndex("MaHoaDon");

                    b.ToTable("PHIEUTHUTIEN");
                });

            modelBuilder.Entity("BookManagementWeb.Models.Entities.Sach", b =>
                {
                    b.Property<int>("MaSach")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaSach"), 1L, 1);

                    b.Property<string>("PhotoUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SachMaSach")
                        .HasColumnType("int");

                    b.Property<int>("SoLuongSach")
                        .HasColumnType("int");

                    b.Property<string>("TacGia")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TenSach")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TheLoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaSach");

                    b.HasIndex("SachMaSach");

                    b.ToTable("SACH");
                });

            modelBuilder.Entity("BookManagementWeb.Models.Entities.CTHoaDon", b =>
                {
                    b.HasOne("BookManagementWeb.Models.Entities.HoaDon", "HoaDon")
                        .WithMany("CTHoaDonCollectionHD")
                        .HasForeignKey("MaHoaDon")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookManagementWeb.Models.Entities.Sach", "Sach")
                        .WithMany("CTHoaDonCollectionSach")
                        .HasForeignKey("MaSach")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HoaDon");

                    b.Navigation("Sach");
                });

            modelBuilder.Entity("BookManagementWeb.Models.Entities.CTPhieuNhapSach", b =>
                {
                    b.HasOne("BookManagementWeb.Models.Entities.PhieuNhapSach", "PhieuNhapSach")
                        .WithMany("CTPhieuNhapSachPN")
                        .HasForeignKey("MaPhieuNhapSach")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookManagementWeb.Models.Entities.Sach", "Sach")
                        .WithMany("CTPhieuNhapSachCollectionSach")
                        .HasForeignKey("MaSach")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PhieuNhapSach");

                    b.Navigation("Sach");
                });

            modelBuilder.Entity("BookManagementWeb.Models.Entities.HoaDon", b =>
                {
                    b.HasOne("BookManagementWeb.Models.Entities.KhachHang", "KhachHang")
                        .WithMany("HoaDonCollectionKH")
                        .HasForeignKey("MaKhachHang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhachHang");
                });

            modelBuilder.Entity("BookManagementWeb.Models.Entities.PhieuThuTien", b =>
                {
                    b.HasOne("BookManagementWeb.Models.Entities.HoaDon", "HoaDon")
                        .WithMany("PhieuThuTienCollection")
                        .HasForeignKey("MaHoaDon")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HoaDon");
                });

            modelBuilder.Entity("BookManagementWeb.Models.Entities.Sach", b =>
                {
                    b.HasOne("BookManagementWeb.Models.Entities.Sach", null)
                        .WithMany("SachList")
                        .HasForeignKey("SachMaSach");
                });

            modelBuilder.Entity("BookManagementWeb.Models.Entities.HoaDon", b =>
                {
                    b.Navigation("CTHoaDonCollectionHD");

                    b.Navigation("PhieuThuTienCollection");
                });

            modelBuilder.Entity("BookManagementWeb.Models.Entities.KhachHang", b =>
                {
                    b.Navigation("HoaDonCollectionKH");
                });

            modelBuilder.Entity("BookManagementWeb.Models.Entities.PhieuNhapSach", b =>
                {
                    b.Navigation("CTPhieuNhapSachPN");
                });

            modelBuilder.Entity("BookManagementWeb.Models.Entities.Sach", b =>
                {
                    b.Navigation("CTHoaDonCollectionSach");

                    b.Navigation("CTPhieuNhapSachCollectionSach");

                    b.Navigation("SachList");
                });
#pragma warning restore 612, 618
        }
    }
}
